name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          cache: true

      - name: Install dependencies
        run: dart pub get

      - name: Analyze source code
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Build and deploy
        uses: ./workflows # specify the relative path to the "ci" folder
        with:
          arg1: value1
          arg2: value2
